swagger: "2.0"
info:
  description: "agilbzin feigin pls :')'"
  version: "4.2.0"
  title: "A Questionable API"
host: "ainain.com"
basePath: "/api"
tags:
- name: "literally us api fam"
  description: "A set of API instructions to wild up the mood"
paths:
  /riddleMeThis:
    get:
      summary: "riddle of the rocks"
      description: "Lemon? Not this time"
      tags:
      - "literally us api fam"
      produces: 
      - "application/json"
      responses:
        200:
          description: ":')"
          schema:
            $ref: "#/definitions/Riddle"
        400:
          description: ":("
  /fireItUp:
    get:
      summary: "#420 #blazeIt"
      tags:
      - "literally us api fam"
      produces:
      - "application/json"
      responses:
        200:
          description: "ayy lmao fam you so lit"
          schema:
            $ref: "#/definitions/Smokey"
        400:
          description: "How can one fail if stoned?"
  /climbMe:
    get:
      summary: "I will sho u de wae"
      tags:
      - "literally us api fam"
      produces:
      - "image/png"
      responses:
        200:
          description: "Follow the queen"
        400:
          description: "You are the fake qween. Buddahs, spit on her"
  /doABarrelRoll:
    get:
      summary: "Hopsy Daisy"
      tags:
      - "literally us api fam"
      produces:
      - "index/html"
      responses:
        200:
          description: "works in google as well"
        400:
          description: "ANGERY"
  /yee:
    get:
      summary: "yee"
      tags:
      - "literally us api fam"
      produces:
      - "video/mp4"
      responses:
        200:
          description: "baba baba ba baba ba baba ba ba ba ba ba ba ba"
        400:
          description: "YEE"
definitions:
  Riddle:
    type: "object"
    properties:
      question:
        type: "string"
      path:
        type: "string"
      key:
        type: "string"
  Smokey:
    type: "object"
    properties:
      count:
        type: "integer"